import * as stylex from '@stylexjs/stylex'

export const styles = stylex.create({
  periodContent: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0rem 0',
    paddingTop: '35px',
    zIndex: 10001,
    position: 'relative',
    isolation: 'isolate',
  },
  periodContentMobile: {
    paddingTop: '20px',
  },
  timeContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.5rem',
    position: 'relative',
    zIndex: 10001,
    width: '100%',
  },
  timeContainerMobile: {
    gap: '0.25rem',
  },
  timeRow: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '1.4rem',
  },
  timeText: {
    fontSize: '1.1rem',
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 1.25,
    margin: 0,
  },
  timeTextMobile: {
    fontSize: '0.95rem',
  },
  dateTimeGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
  },
  dateTimeGroupMobile: {
    gap: '0.5rem',
  },
  timezoneWarningContainer: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    zIndex: 9999,
    isolation: 'isolate',
  },
  timezoneWarningButton: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    borderWidth: '2px',
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    fontWeight: 'bold',
    fontSize: '0.9rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s ease',
    position: 'relative',
    zIndex: 10,
    padding: 0,
    WebkitTapHighlightColor: 'transparent',
    flexShrink: 0,
    ':hover': {
      transform: 'scale(1.1)',
    },
  },
  timezoneWarningButtonMobile: {
    width: '22px',
    height: '22px',
    fontSize: '0.85rem',
  },
  timezoneWarningButtonLight: {
    color: '#ff6b35',
    borderColor: '#ff6b35',
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    ':hover': {
      backgroundColor: 'rgba(255, 107, 53, 0.2)',
      boxShadow: '0 0 12px rgba(255, 107, 53, 0.3)',
    },
  },
  timezoneWarningButtonDark: {
    color: '#ffa726',
    borderColor: '#ffa726',
    backgroundColor: 'rgba(255, 167, 38, 0.15)',
    ':hover': {
      backgroundColor: 'rgba(255, 167, 38, 0.25)',
      boxShadow: '0 0 12px rgba(255, 167, 38, 0.4)',
    },
  },
  timezonePopup: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    right: 0,
    width: '280px',
    padding: '12px 16px',
    borderRadius: '8px',
    fontSize: '0.85rem',
    lineHeight: 1.4,
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.3)',
    backdropFilter: 'blur(10px)',
    zIndex: 9999,
    willChange: 'opacity, transform',
    transition: 'opacity 0.2s ease-out, transform 0.2s ease-out',
  },
  timezonePopupHidden: {
    opacity: 0,
    transform: 'translateY(-10px) scale(0.95)',
    pointerEvents: 'none',
  },
  timezonePopupVisible: {
    opacity: 1,
    transform: 'translateY(0) scale(1)',
    pointerEvents: 'auto',
  },
  timezonePopupMobile: {
    width: '250px',
    fontSize: '0.8rem',
    padding: '10px 14px',
    right: '-20px',
  },
  timezonePopupSmallMobile: {
    width: '220px',
    right: '-40px',
  },
  timezonePopupLight: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    color: '#333333',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 107, 53, 0.3)',
  },
  timezonePopupDark: {
    backgroundColor: 'rgba(30, 30, 30, 0.95)',
    color: '#e0e0e0',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 167, 38, 0.3)',
  },
  lightText: {
    color: '#000846',
  },
  darkText: {
    color: '#b8c5ff',
  },
})